export const ESW업체 = [
  {
    C_NAME: "㈜무스마",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜시지온",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "굿써클",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "베스트에프에이㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜경성테크놀러지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜기원솔루텍",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜바질컴퍼니",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜사운드리더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜니더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜AIS",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에코마린",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "유이수㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜테스타",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜페이타랩",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜코봇",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "프엠테크놀리지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "화진기업㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "KMG",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜한백전자",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 5,
  },
  {
    C_NAME: "㈜제이코퍼레이션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "지니에듀테크㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜제이코퍼레이션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "수상에스티㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜삼우이모션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜유니크온",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜클린스쿨",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
];
