export const ESW업체 = [
  {
    C_NAME: "㈜무스마",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "mcas 프로젝트의 개발 및 업데이트",
    필요역량:
      "Fontend: React/ MobX/ React-Native/ Typescript, Backend: Node.js/ DB",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜시지온",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "Frontend: HTML, CSS, Javascript와 모던 웹 프론트 앤드",
    필요역량:
      "2.Backend: 해당()내용에 대한 이해(Node JS/ REST API/ 웹 서비스(http 등))",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "굿써클",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "모바일 게임(AOS,iOS)개발(Unity 엔진을 이용한 프로그래밍",
    필요역량: "Unity프로그래밍 능력(★)(Unity 프로그래밍능력",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "베스트에프에이㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "기존 설치된 공장자동화설비(FA) 관련 소프트웨어의 유지",
    필요역량: "1.(우대) PAC(산업용 소프트웨어) 등 메카트로닉스",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜경성테크놀러지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "인공지능 데이터 수집, 가공 및 검수",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜기원솔루텍",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜바질컴퍼니",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "하드웨어설계(PCB 회로기판 설계), 소프트웨어설계(인공지능)",
    필요역량: "해당 업무내용 관련 역량",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜사운드리더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜니더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "자사 서비스 유지 및 보수/ 서비스 내 신규 컨텐츠",
    필요역량: "지속성장가능한 인재/ 문재가 생겼을 때 원할한 소통이 가능한 분",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜AIS",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용:
      "Backend: 데이터이동 파이프, Error시 디버깅, Fontend: React Native 역량(★)",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에코마린",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "유이수㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "수출전자상거래 솔루션 개발",
    필요역량:
      "Fontend: HTML, CSS, JS, Backend: node, python 등 중 1가지에 숙달",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜테스타",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜페이타랩",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜코봇",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "로봇 프로그램 엔지니어",
    필요역량: "웹기반 자바스크립트, C계열(C, C# 등)",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "프엠테크놀리지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "소프트웨어 개발((시작)기획 → (숙련,검증)SW개발)",
    필요역량: "프로그래밍개발능력(파이썬 등 기본적인 것)+ 인성, 끈기",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "화진기업㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "KMG",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜한백전자",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "전자부품연구 개발(ETRI, 정부출연연구소, 기업부설연구소)",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 5,
  },
  {
    C_NAME: "㈜제이코퍼레이션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "인공지능 소프트웨어, 영상 검사기 제작 및 소프트웨어",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "지니에듀테크㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "3D프린터,드론,아두이노 관련 제품 개발 및 제조 판매",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "수상에스티㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜삼우이모션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용:
      "직무교육 VR 솔루션 제작, 산업용 비대면 플랫폼 SmartWork 솔루션 개발",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜유니크온",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "스마트 LED조명제어 시스템 개발 및 제조",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜클린스쿨",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "위생안전제품개발 및 제조, 소프트웨어개발 및 판매",
    필요역량: "",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
];
