export const SW업체 = [
  {
    C_NAME: "㈜BNK시스템",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "금융IT 전반 SW개발(전산 포함)",
    필요역량: "프로그래밍언어(Java, C), 정보처리기사, 실무 위주의 프로젝트",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜마이다스아이티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜잉카인터넷",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "QA업무(고졸은 SW개발업무 안함)",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜아트랩소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "SW개발",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜엑셈",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "Front개발/ Server개발",
    필요역량: "DB(Oracle 등) 구조 이해 필요",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜토즈",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "W개발(향후 AI개발도 계획)",
    필요역량: "개발 역량 중요(★): 유니티, C# 활용능력",
    DEPARTMENT: "SW",
    C_COUNT: 5,
  },
  {
    C_NAME: "다운정보통신㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "SW/웹 개발 관련 기초 업무",
    필요역량: "학교 기초 실무지식(특정 언어를 지향X) + 사회성(★ 조직활동)",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜드림아이티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "기술영업, 시스템엔지니어, IT컨설팅, 교육서비스 강사",
    필요역량:
      "소프트웨어자산관리자 자격증, 프로그래밍 언어(C,C++,C#,Java, Python 등)",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜블루솜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "앱 개발",
    필요역량: "개발 역량 중요(★): 유니티, C# 활용능력",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜리나소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "모바일 앱/웹 개발(채용 후 일정 교육 기간 필요)",
    필요역량: "직무관련 기초적 지식 필요",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에버스톤",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "모바일 게임,모바일 앱",
    필요역량: "A. 해당 직무의 이해도 B. 커뮤니케이션 능력 C. 인성",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜오픈놀",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "Front개발/Backend개발",
    필요역량: " 기본적인 프로그래밍 능력 필요",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "㈜더재무컨설팅",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "앱/웹 개발, Backend개발",
    필요역량: "다양한 언어 습득 우대",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에이블리스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "연구개발,SW개발",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜비트시스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "블록체인&소프트웨어&플랫폼, AI&빅데이터&IoT,",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  ,
  {
    C_NAME: "㈜큐티티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "모바일 자가 구강 검진 어플리케이션, 웹기반 단체용 소프트웨어",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 5,
  },
  {
    C_NAME: "㈜토탈소프트뱅크",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "선박, 해운, 항만, 물류소프트웨어 개발, 교육용 시뮬레이터 개발",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "㈜리커시브소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "iOS/Android App 개발, Cloud based App 개발",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜이씨스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "전자무역/물류 솔루션 개발 및 보급사업, 기업정보화 컨설팅",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜유피체인",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "가상자산거래소 개발, 건설 PMIS 공급, 전자 상거래 서비스",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜어니언팜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용:
      "플랫폼에 따른 UI 개발과 백엔드 시스템 및 백오피스 개발, 다양한 기능",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜파운더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용:
      "B2B 업무 기능 통합 솔루션 기능 개발, 영상 관련 서비스, AWS, Azure, Vimeo",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜아우름플래닛",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "인터넷 하이라이팅을 기반으로 한 정보탐색 플랫폼 서비스",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜라플라스테크놀로지스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "프론트엔드 개발",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜아데나소프트웨어",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜와이즈넛",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "SQL소프트㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "브레인즈컴퍼니㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "응용 소프트웨어 개발 및 공급업",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜셀디코리아",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "응용 소프트웨어 개발 및 공급업",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜럭스로보",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "로봇 운용 소프트웨어 관련 엔지니어",
    필요역량: "C, C+ 등",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜한컴위드",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "시스템 소프트웨어 개발 및 공급업",
    필요역량: "",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에덴룩스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "게임/앱/웹(홈페이지) 개발 관리",
    필요역량: "개발 역량 중요(★): 유니티, C# 활용능력",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "매직큐브",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "혼자서 프로그래밍할 능력",
    필요역량: "(우대)포트폴리오(실제 만든 게임을 정리)",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜피엘지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "SW개발",
    필요역량: "소프트웨어 개발 능력, 경험 중요",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜리얼메이커",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "앱 개발",
    필요역량: "포트폴리오(프로그램의 이해 및 운용 능력 확인)",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜팩앤롤",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "거래처에 구축된 MES(스마트공장제어프로그램)의 유지 및 보수",
    필요역량: "프로그램 개발 및 ERP 구축을 위한 C언어 계열 프로그래밍 능력",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜인터버드",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "프로그램 개발",
    필요역량:
      "프로그램 개발능력(자바 위주, 앱(안드로이드/iOS) 개발 위주), 프로젝트 경험 및 역량",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "더웰",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "앱/서버 개발",
    필요역량: "실무에서 바로 쓸 수 있을 역량",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜팜코브",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    업무내용: "SW개발, 데이터분석",
    필요역량: ".(우대)프로젝트, 소프트웨어개발 등의 경험이 있는 인재",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
];
