export const SW업체 = [
  {
    C_NAME: "㈜BNK시스템",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜마이다스아이티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜잉카인터넷",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜아트랩소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜엑셈",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜토즈",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 5,
  },
  {
    C_NAME: "다운정보통신㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜드림아이티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜블루솜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜리나소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에버스톤",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜오픈놀",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "㈜더재무컨설팅",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에이블리스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜비트시스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  ,
  {
    C_NAME: "㈜큐티티",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 5,
  },
  {
    C_NAME: "㈜토탈소프트뱅크",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "㈜리커시브소프트",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜이씨스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜유피체인",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜어니언팜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜파운더",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜아우름플래닛",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜라플라스테크놀로지스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜아데나소프트웨어",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜와이즈넛",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "SQL소프트㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 3,
  },
  {
    C_NAME: "브레인즈컴퍼니㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜셀디코리아",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜럭스로보",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜한컴위드",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜에덴룩스",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "매직큐브",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜피엘지",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜리얼메이커",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜팩앤롤",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜인터버드",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "더웰",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜팜코브",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "SW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜제이코퍼레이션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "수상에스티㈜",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜삼우이모션",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
  {
    C_NAME: "㈜유니크온",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 1,
  },
  {
    C_NAME: "㈜클린스쿨",
    X_CNTS: "지도 X좌표",
    Y_DNTS: "지도 Y좌표",
    DEPARTMENT: "ESW",
    C_COUNT: 2,
  },
];
